api_platform:
    title: VTT Évasion Ludres
    version: 1.0.0
    defaults:
        pagination_enabled: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ["application/json"]

when@dev:
    api_platform:
        defaults:
            stateless: false