framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'contact@vttevasionludres.fr'
        headers:
            from: 'VTT Evasion Ludres <contact@vttevasionludres.fr>'
            bcc: 'pab54@free.fr'