<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231101150612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sworn_certification (id INT AUTO_INCREMENT NOT NULL, licence_id INT DEFAULT NULL, label LONGTEXT NOT NULL, value TINYINT(1) NOT NULL, INDEX IDX_79ED8B7726EF07C9 (licence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE sworn_certification ADD CONSTRAINT FK_79ED8B7726EF07C9 FOREIGN KEY (licence_id) REFERENCES licence (id)');
        $this->addSql('ALTER TABLE health DROP at_least_one_positve_response');
        $this->addSql('ALTER TABLE registration_step ADD personal TINYINT(1) DEFAULT 0 NOT NULL');

        $registrationsSteps = $this->connection->executeQuery('SELECT id FROM `registration_step`')->fetchAllAssociative();
        $registrationsStepsIds = array_column($registrationsSteps, 'id');

        $registrationSteps = [
            [2, 'Tarifs', NULL, 6, 1, '<p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif">Ch&egrave;ques vacances, Coupons sport (ANCV), Pass&#39;Sport, Pass&#39;Jeunes accept&eacute;s</span></p><p style="text-align:justify"><span style="font-size:12px"><strong><u><span style="color:#e74c3c">CE MONTANT COMPREND POUR 1 ANNEE : VOTRE LICENCE + ASSURANCE + COTISATION CLUB </span></u></strong></span></p><p style="text-align:justify"><span style="font-family:Arial,Helvetica,sans-serif"><strong>IMPORTANT:</strong><br />Voir d&eacute;tails des garanties assurances f&eacute;d&eacute;rales <strong><span style="color:#c0392b">QUE VOUS DEVREZ REDONNER AU CLUB</span></strong> avec votre bulletin d&rsquo;inscription.<br />ATTENTION&nbsp; :<br />POUR DECLARER VOS SINISTRES, vous devez vous connecter sur votre espace adh&eacute;rent sur le site de la f&eacute;d&eacute;ration : <strong><span style="color:#c0392b">ffct.org</span></strong> et en informer votre club. Conservez toujours vos factures d&#39;achats d&#39;&eacute;quipements. L&#39;option Grand Braquet n&#39;est prise en consid&eacute;ration qu&#39;apr&egrave;s inscription et seulement &agrave; partir du 1er&nbsp;janvier de l&#39;ann&eacute;e suivante. Pour les inscriptions en cours d&#39;ann&eacute;e jusqu&#39;&agrave; fin d&eacute;cembre, le licenci&eacute; est assur&eacute;&nbsp;uniquement en petit braquet.<br />VOTRE LICENCE est d&eacute;mat&eacute;rialis&eacute;e. Vous la recevrez par mail d&egrave;s que votre adh&eacute;sion sera effective sur le site f&eacute;d&eacute;ral. Elle comporte <span style="color:#c0392b"><strong>vos identifiants pour vous connecter sur le site f&eacute;d&eacute;ral (ffct.org) </strong></span>notamment en cas de&nbsp;d&eacute;claration de sinistre.</span></p>', NULL, 3, 4, 3, 1],
            [3, 'Questionnaire de santé ffvélo', NULL, 1, 0, NULL, NULL, 0, 7, 1, 1],
            [4, 'Informations du parent ou tuteur de l\'enfant', NULL, 11, 2, NULL, 1, 3, 2, 3, 0],
            [5, 'Informations de l\'adhérent', NULL, 10, 1, NULL, NULL, 3, 2, 3, 0],
            [7, 'Assurance', 'NOTICE-D-INFORMATION-DU-LICENCIE-2023-A-SIGNER-634057d46675f.pdf', 5, 1, '<p>{{ boutons_radio_assurance }}</p>', NULL, 0, 5, 1, 0],
            [8, 'Autorisations adulte', NULL, 4, 1, '<h2>Droit &agrave; l&#39;image</h2><p>Dans le cadre de nos activit&eacute;s, nous sommes amen&eacute;s &agrave; prendre des photos, des films ou des enregistrements sonores des membres du club pratiquant le VTT seul ou en groupe lors de nos sorties ou de diverses manifestations sportives. C&#39;est dans cet objectif que nous vous demandons l&rsquo;autorisation pour &ecirc;tre photographi&eacute;, film&eacute; ou enregistr&eacute;, et ce uniquement pour la communication de notre club. L&#39;association s&#39;interdit express&eacute;ment<br />de proc&eacute;der &agrave; une exploitation des photographies, films et/ou interviews susceptibles de porter atteinte &agrave; la vie priv&eacute;e ou &agrave; la r&eacute;putation de ses adh&eacute;rents.</p><p>Je soussign&eacute;&nbsp; {{ prenom_nom }} {{ autorisation_droit_image }}&nbsp;le club VTT Evasion Ludres &agrave; utiliser ou faire utiliser ou reproduire ou faire reproduire mon image et ma voix. Je me reconnais enti&egrave;rement rempli de mes droits et je ne pourrai pr&eacute;tendre &agrave; aucune r&eacute;mun&eacute;ration pour l&#39;exploitation des droits vis&eacute;s &agrave; la pr&eacute;sente.</p><p>{{ bouton_droit_image }}</p><p>&nbsp;</p><h2><span style="font-size:16px"><strong>Sant&eacute;</strong></span></h2><p>J&rsquo;autorise les moniteurs f&eacute;d&eacute;raux ainsi que les initiateurs f&eacute;d&eacute;raux ou tout autre futurs moniteurs et/ou initiateurs, &agrave; prendre toute d&eacute;cision concernant les soins d&rsquo;urgences qui s&rsquo;av&eacute;reraient n&eacute;cessaires et/ou obligatoires me concernant lors des activit&eacute;s organis&eacute;es par le club.&nbsp;Je les autorise &agrave; transmettre aux services m&eacute;dicaux comp&eacute;tents les renseignements m&eacute;dicaux me concernant.</p>', 2, 3, 6, 3, 0],
            [9, 'Téléchargement', NULL, 7, 1, '<p><span style="font-family:Arial,Helvetica,sans-serif"><strong>Votre inscription est presque termin&eacute;e.</strong></span></p><p><span style="font-family:Arial,Helvetica,sans-serif"><span style="color:#e74c3c">T&eacute;l&eacute;chargez et imprimez votre dossier afin de valider votre inscription</span>. Il ne reste plus qu&#39;&agrave; le signer &agrave; 2 endroits (coupon assurance et bulletin d&#39;inscription) et &agrave; transmettre les documents au club avec votre paiement et certificat m&eacute;dical si besoin <strong>(OBLIGATOIRE POUR TOUTE NOUVELLE INSCRIPTION).</strong></span></p><p><u><strong>Nous vous avons envoy&eacute; un mail avec votre identifiant provisoire</strong></u></p><p><span style="font-family:Arial,Helvetica,sans-serif">La f&eacute;d&eacute;ration FFCT exige un certificat m&eacute;dical dat&eacute; DE MOINS DE 12 MOIS de non contre-indication &agrave; la pratique du VTT pour la 1&egrave;re prise de licence. Pour les r&eacute;inscriptions, c&#39;est en fonction du type de licence que vous choisirez (tous les 5 ans en formule RANDO et tous les 3 ans en formule SPORT ) et vous devrez renseigner le questionnaire de sant&eacute; que vous conserverez (ne pas le redonner au club, donn&eacute;es personnelles).</span></p><p><span style="color:#e74c3c"><strong><span style="font-family:Arial,Helvetica,sans-serif">Tout dossier incomplet ne sera pas accept&eacute; et l&#39;inscription ne sera pas valid&eacute;e</span></strong></span></p>', NULL, 1, 9, 1, 0],
            [10, 'Autorisations mineur', NULL, 4, 1, '<p style="text-align:justify">Je soussign&eacute; {{ prenom_nom_parent }} Inscrit et autorise l&#39;enfant {{ prenom_nom_enfant }} &agrave; participer aux s&eacute;ances p&eacute;dagogiques et &agrave; v&eacute;lo de l&rsquo;Ecole VTT Evasion Ludres.</p><p style="text-align:justify">J&rsquo;autorise &eacute;galement les moniteurs f&eacute;d&eacute;raux ainsi que les initiateurs f&eacute;d&eacute;raux ou tout autre futurs moniteurs et/ou initiateurs, &agrave; prendre toute d&eacute;cision concernant les soins d&rsquo;urgences qui s&rsquo;av&eacute;reraient n&eacute;cessaires et/ou obligatoires concernant mon enfant lors des activit&eacute;s organis&eacute;es par le club.&nbsp;Je les autorise &agrave; transmettre aux services m&eacute;dicaux comp&eacute;tents les renseignements m&eacute;dicaux relatifs &agrave; mon enfant.</p><h2>Retour au domicile</h2><p style="text-align:justify">J&rsquo;autorise mon enfant &agrave; rejoindre seul le domicile &agrave; l&rsquo;issue de la s&eacute;ance. (- 12 ans exclu de rejoindre seul). Pour ce faire je m&rsquo;engage &agrave; lui fournir un gilet jaune fluo ainsi qu&rsquo;un dispositif d&rsquo;&eacute;clairage avant (blanc) et arri&egrave;re (rouge)</p><p>{{ bouton_retour_domicile }}</p><h2>Droit &agrave; l&#39;image</h2><p style="text-align:justify">Dans le cadre de nos activit&eacute;s, nous sommes amen&eacute;s &agrave; prendre des photos, des films ou des enregistrements sonores des membres du club pratiquant le VTT seul ou en groupe lors de nos sorties ou de diverses manifestations sportives. C&#39;est dans cet objectif que nous vous demandons l&rsquo;autorisation pour &ecirc;tre photographi&eacute;, film&eacute; ou enregistr&eacute;, et ce uniquement pour la communication de notre club. L&#39;association s&#39;interdit express&eacute;ment de proc&eacute;der &agrave; une exploitation des photographies, films et/ou interviews susceptibles de porter atteinte &agrave; la vie priv&eacute;e ou &agrave; la r&eacute;putation de ses adh&eacute;rents.<br />Je soussign&eacute;&nbsp;{{ prenom_nom_parent }} {{ autorisation_droit_image }} le club VTT Evasion Ludres &agrave;&nbsp;utiliser ou faire utiliser ou reproduire ou faire reproduire l&#39;image et la voix de mon enfant {{ prenom_nom_enfant }}. Je me&nbsp; reconnais enti&egrave;rement rempli de mes droits et je ne pourrai pr&eacute;tendre &agrave; aucune r&eacute;mun&eacute;ration pour l&#39;exploitation des droits vis&eacute;s &agrave; la pr&eacute;sente.</p><p>{{ bouton_droit_image }}</p>', 1, 3, 6, 3, 0],
            [11, 'Validation', NULL, 9, 1, '<p style="text-align:center">Voici le r&eacute;capitulatif des informations saisies.</p><p style="text-align:center">Nous vous invitons &agrave; les relire et &agrave; les modifier si besoin.</p><p style="text-align:center">Apr&egrave;s validation, aucune modification ne sera possible.</p><p style="text-align:center">NE PAS OUBLIER DE REDONNER AU CLUB VOTRE BULLETIN D&#39;INSCRIPTION ET LE COUPON ASSURANCE,</p><p style="text-align:center"><strong>LES</strong> <strong>DEUX&nbsp;DOIVENT ETRE SIGNES</strong></p>', NULL, 1, 8, 1, 0],
            [12, 'Questionnaire de santé ffvélo [pdf)', 'Questionnaire-sante-2023-65421e14037ba.pdf', 1, 1, NULL, NULL, 0, 7, 2, 1],
            [13, 'Dossier d\'inscription essai', NULL, 0, 1, '<p>{{ entete }}</p><table border="0" cellpadding="1" cellspacing="1" class="table-fixed" style="width:100%"><tbody><tr><td><img alt="" src="/images/logo-pdf.jpg" style="height:110px; width:110px" /></td><td colspan="3" rowspan="1"><h1 style="text-align:center">{{ titre_licence }} - {{ saison }}</h1></td><td><img alt="" src="/images/ffvelo-logo-square-75x75.png" style="float:right; height:50px; width:50px" /></td></tr><tr><td style="height:0px">&nbsp;</td><td style="height:0px">&nbsp;</td><td style="height:0px">&nbsp;</td><td style="height:0px">&nbsp;</td><td style="height:0px">&nbsp;</td></tr></tbody></table><p>{{ entete }}</p><p>{{ pied_page }}</p><p>&nbsp;</p><table class="table-fixed" style="width:100%"><tbody><tr><td style="width:100%">{{ attestations_sur_honneur }}</td></tr><tr><td style="width:100%">&nbsp;</td></tr><tr><td style="width:100%"><strong>Type d&#39;assurance : </strong>{{ type_assurance}}</td></tr><tr><td style="width:100%">{{ cotisation }}</td></tr></tbody></table><p>&nbsp;</p><p>IL EST IMPERATIF DE SIGNER L&#39;INFORMATION D&#39;ASSURANCE GRATUITE JOINTE A CE DOCUMENT</p><p>&nbsp;</p><table class="table-fixed" style="width:100%"><tbody><tr><td>Fait &agrave; Ludres le {{ date }}</td><td>Signature : (pr&eacute;c&eacute;d&eacute;e de la mention &lsquo;&rsquo;Lu et approuv&eacute;&rsquo;&rsquo;)</td></tr></tbody></table><p>{{ pied_page }}</p>', NULL, 2, 1, 0, 0],
            [14, 'Dossier d\'inscription final', NULL, 0, 1, '<p>{{ entete }}</p><table border="0" cellpadding="1" cellspacing="1" class="table-fixed" style="width:100%"><tbody><tr><td><img alt="" src="/images/logo-pdf.jpg" style="height:110px; width:110px" /></td><td colspan="3" rowspan="1"><h1 style="text-align:center">{{ titre_licence }} - {{ saison }}</h1></td><td><img alt="" src="/images/ffvelo-logo-square-75x75.png" style="float:right; height:50px; width:50px" /></td></tr><tr><td style="height:1px">&nbsp;</td><td style="height:1px">&nbsp;</td><td style="height:1px">&nbsp;</td><td style="height:1px">&nbsp;</td><td style="height:1px">&nbsp;</td></tr></tbody></table><p>{{ entete }}</p><p>{{ pied_page }}</p><table class="table-fixed" style="width:100%"><tbody><tr><td style="width:100%">{{ attestations_sur_honneur }}</td></tr><tr><td style="width:100%">&nbsp;</td></tr><tr><td style="width:100%"><strong>Type d&#39;assurance : </strong>{{ type_assurance}}</td></tr><tr><td style="width:100%">{{ cotisation }}</td></tr><tr><td style="width:100%">{{ necessite_sertificat_medical }}</td></tr></tbody></table><p>&nbsp;</p><table class="table-fixed" style="width:100%"><tbody><tr><td>Fait &agrave; Ludres le {{ date }}</td><td>Signature : (pr&eacute;c&eacute;d&eacute;e de la mention &lsquo;&rsquo;Lu et approuv&eacute;&rsquo;&rsquo;)</td></tr></tbody></table><p>&nbsp;</p><p>{{ pied_page }}</p>', NULL, 0, 1, 2, 0],
            
            [15, 'Reconnaître les symptômes cardiaques', 'reconnaitre-les-symptomes-cardiaques-65428a4b99b1a.pdf', 1, 2, NULL, NULL, 0, 7, 4, 1],
            [16, 'Facteurs de risques et pathologies cardiaques', 'facteurs-de-risques-et-pathologies-cardiaques-6543d72cc6835.pdf', 1, 3, NULL, NULL, 0, 7, 4, 1],
            [17, 'Les problématiques liées au sport', 'les-problematiques-liees-au-sport-6543e17c1835a.pdf', 1, 4, NULL, NULL, 0, 7, 4, 1],
            [18, 'Assurance (pages 1 et 2)', 'NOTICE-INFORMATION-DU-LICENCIE-A-SIGNER-SAISON-2024-1-2-6545e88db6771.pdf', 5, 2, NULL, NULL, 2, 5, 2, 1],
            [19, 'Assurance (pages 3)', 'NOTICE-INFORMATION-DU-LICENCIE-A-SIGNER-SAISON-2024-3-654600a65beea.pdf', 5, 3, NULL, NULL, 2, 5, 2, 0]];
            
            $keys = ['id', 'title', 'filename', 'form', 'orderBy', 'content', 'category', 'testingRender', 'group', 'finalRender', 'personal'];
            
            $this->addSql('DELETE FROM `registration_step` WHERE `id`=1');

            foreach($registrationSteps as $step) {
                $registrationStep = [];
                foreach($step as $key => $value) {
                    $registrationStep[$keys[$key]] = $value;
                }
                if (in_array($registrationStep['id'], $registrationsStepsIds)) {
                    $this->addSql('UPDATE `registration_step` SET `title`=:title,`filename`=:filename,`form`=:form,`order_by`=:orderBy,`content`=:content,`category`=:category,`testing_render`=:testingRender,`registration_step_group_id`=:group,`final_render`=:finalRender,`personal`=:personal WHERE `id`=:id', $registrationStep);
                } else {
                    $this->addSql('INSERT INTO `registration_step` (`id`, `title`, `filename`, `form`, `order_by`, `content`, `category`, `testing_render`, `registration_step_group_id`, `final_render`, `personal`) VALUES (:id, :title, :filename, :form, :orderBy, :content, :category, :testingRender, :group,:finalRender, :personal)', $registrationStep);
                }
            };
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sworn_certification DROP FOREIGN KEY FK_79ED8B7726EF07C9');
        $this->addSql('DROP TABLE sworn_certification');
        $this->addSql('ALTER TABLE registration_step DROP personal');
        $this->addSql('ALTER TABLE health ADD at_least_one_positve_response TINYINT(1) DEFAULT 0 NOT NULL');
    }
}
