<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211006182356 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("INSERT INTO `product` (`id`, `name`, `content`, `filename`, `price`, `is_disabled`, `ref`) VALUES
        (1, 'Maillot MC été Classique', '<p><strong>ZIP INT&Eacute;GRAL</strong><br />\r\nCe maillot en tissu Coolmax et manches raglan, est le produit pl&eacute;biscit&eacute; par nos clubs. Les panneaux lat&eacute;raux en &laquo;TIME OUT&raquo; &eacute;vacuant instantan&eacute;ment l&rsquo;humidit&eacute; s&egrave;che tr&egrave;s vite et permet &agrave; l&rsquo;air de circuler pour maintenir le corps &agrave; la bonne temp&eacute;rature. Sa coupe ergonomique est renforc&eacute;e par une bande &eacute;lastique silicon&eacute;e &agrave; la taille, ainsi le maillot reste parfaitement en place quelle que soit la position sur le v&eacute;lo. Un zip s&eacute;curit invisible qui respectera votre design et/ou marquage sponsor permet de bloquer le curseur &agrave; la hauteur d&eacute;sir&eacute;e. Les 3 poches renforc&eacute;es en double couture assurent un bon maintien de votre ravitaillement. 1 poche zipp&eacute;e arri&egrave;re</p>', '1801-PRO-C-615608ef1d375.png', 35, 0, 'Réf. 1801 A'),
        (2, 'Maillot MC été Pro (ajusté)', '<p><strong>PRO GORA</strong><br />\r\nCe maillot Pro aux performances a&eacute;rodynamiques &eacute;lev&eacute;es, con&ccedil;u pour rouler dans les conditions les plus chaudes et les plus humides. Le tissu &eacute;vacuant instantan&eacute;ment l&rsquo;humidit&eacute; s&egrave;che tr&egrave;s vite et permet &agrave; l&rsquo;air de circuler pour maintenir le corps &agrave; la bonne temp&eacute;rature. Son col ouvert d&eacute;gage le cou pour vous permettre de rester &agrave; l&rsquo;aise et de respirer. Les manches en Lycra &ldquo;Fan&rdquo; contribuent &agrave; la ventilation et au bien &ecirc;tre du cycliste. Une bande de maintien remplace l&rsquo;&eacute;lastique au niveau de l&rsquo;abdomen pour &eacute;viter toute compression. Un zip s&eacute;curit invisible qui respectera votre design et/ou marquage sponsor permet de bloquer le curseur &agrave; la hauteur d&eacute;sir&eacute;e. Les 2 poches renforc&eacute;es en double couture assurent un bon maintien de votre ravitaillement. Une poche &eacute;cologique sur le cot&eacute; droit sera tr&egrave;s utile lors de vos sorties et courses. &nbsp;1 poche zipp&eacute;e arri&egrave;re</p>', '1801-PRO-C-61589e882cb4e.png', 42, 0, 'Réf. 1801 PRO C'),
        (3, 'Maillot VTT ML Coupe ample', '<p>MAILLOTS LONGUES MANCHES BMX - FREE RIDE - VTT DESCENTE<br />\r\nQuelle que soit la discipline BMX (Race, Dirt, Street, Flat&hellip;), il s&rsquo;agit d&rsquo;assurer une bonne protection du pilote BMX. Ce maillot de coupe large pour y placer les protections avec un col en V tr&egrave;s l&eacute;ger et ventil&eacute; offre un confort d&#39;utilisation tout au long de la saison et se montre particuli&egrave;rement performant pour les pratiques engag&eacute;es.</p>', 'Coupe-ample-Ref-1806-A-Ref-61-61589f45bd929.png', 30, 0, 'Réf. 1806 A (Réf.61)'),
        (4, 'Body Coupe-Vent Gamex', '<p>Le Body est con&ccedil;u en mati&egrave;re &quot;Gamex&quot; de derni&egrave;re g&eacute;n&eacute;ration, ce dernier est pr&eacute;vu pour la course et les sorties estivales tout en assurant une protection contre les temps plus venteux. Avec un zip int&eacute;gral, et un tissu l&eacute;ger il est facile &agrave; mettre et &agrave; ranger. Il dispose de biais r&eacute;fl&eacute;chissants aux emmanchures pour accro&icirc;tre la visibilit&eacute; lors de vos sorties. Nous proposons, en option, 2 ouvertures avec biais r&eacute;fl&eacute;chissants dans le bas du dos sur la version filet (1807B). Cela permet un acc&egrave;s facile aux poches de votre &eacute;quipement (Maillot, Maillot manches longues,...). Ce body est &eacute;galement disponible en version Dos plein (1807C) avec un tissu &quot;Gamex&quot; comme le devant permettant d&rsquo;accro&icirc;tre votre protection contre le vent.</p>', 'Body-Coupe-Vent-Gamex-Ref-1807-B-61599b3ee0771.png', 40, 0, 'Réf. 1807 B'),
        (5, 'Veste coupe-Vent ML Gamex', '<p>Cette veste l&eacute;g&egrave;re est con&ccedil;ue pour une utilisation courante. Sa coupe vous permettra de l&rsquo;associer avec des produits plus ou moins chauds, vous pourrez ainsi affronter tout type de temps. Le Gamex &eacute;tant une mati&egrave;re coupe vent et l&eacute;g&egrave;rement d&eacute;perlante, Le Windtek pluie donnera satisfaction sous la pluie. La fluidit&eacute; de ces 2 mati&egrave;res permettra de les ranger dans la poche arri&egrave;re de votre maillot. Les bandes de c&ocirc;t&eacute; extensibles permettront d&rsquo;adapter le produit &agrave; tous les cyclistes. La veste est munie d&rsquo;un zip frontal int&eacute;gral. Sa fonction &laquo; Securit &raquo; vous permettra de bloquer la fermeture &agrave; l&rsquo;endroit souhait&eacute;. Un rabat emp&ecirc;chera la pluie et le vent de passer &agrave; la fermeture.</p>', 'Coupe-Vent-ML-Gamex-Ref-1808-A-61599bf7a4343.png', 50, 0, 'Réf. 1808 A'),
        (6, 'Manchettes', '<p>Les manchettes Lycra UV offrent une haute protection contre les rayons UV. La base de la manchette est en polyester qui aide &agrave; maintenir un excellent contr&ocirc;le de l&#39;humidit&eacute;.<br />\r\nDu silicone &agrave; double face est utilis&eacute; dans la partie sup&eacute;rieure pour assurer une adh&eacute;rence parfaite et &eacute;viter qu&#39;elles ne descendent lors des sorties.<br />\r\nElles s&rsquo;ajusteront parfaitement &agrave; votre morphologie pour un effet seconde peau.</p>', 'Manchettes-Ref-1831-A-61599d4a98b2c.png', 10, 0, 'Réf. 1831 A'),
        (7, 'Veste Mi-saison Wind-Tek', '<p><strong>EN WIND-TEK + TISSU ISOTHERM</strong><br />\r\n<br />\r\nNotre veste demi-saison est un produit con&ccedil;u pour vous permettre de rouler sereinement lors des sorties automnales et pluvieuse. Sa coupe vous permettra de l&rsquo;associer avec des produits plus ou moins chaud, vous pourrez ainsi affronter tous type de temp&eacute;rature selon vos besoins. Tr&egrave;s appr&eacute;ci&eacute;e comme produit de demi saison, elle est munie de trois poches arri&egrave;re qui vous permettront d&rsquo;emmener votre ravitaillement et une quatri&egrave;me poche zipp&eacute;e qui gardera vos clefs et t&eacute;l&eacute;phone en lieu s&ucirc;r. Pour votre s&eacute;curit&eacute; deux bandes r&eacute;fl&eacute;chissantes sont appos&eacute;es sur les poches arri&egrave;re pour vous assurer une bonne visibilit&eacute;. Un produit passe partout qui ravira aussi bien les cyclistes sur route que les v&eacute;t&eacute;tistes.</p>', 'Veste-Mi-saison-Wind-Tek-Ref-1810-M-6159a04fef35d.png', 55, 0, 'Réf. 1810 M'),
        (8, 'Veste Thermique Wind-Tek', '<p>Notre veste hiver PROGORA sera votre alli&eacute;e pour d&eacute;fier les conditions m&eacute;t&eacute;os les plus fra&icirc;ches. La veste est en tissu WINDTEK ZEROTEK, ce tissu technique contient une membrane coupe vent tr&egrave;s efficace et son tissu gratt&eacute; vous apportera un maximum de chaleur. La coupe est ajust&eacute;e et la grande souplesse du tissu vous permettra des mouvements confortables dans toutes les positions. Pour &eacute;viter les entr&eacute;es d&rsquo;air frais, les manches sont finies par un manchon, et le col est montant. La fermeture zipp&eacute;e type &laquo;s&eacute;curit &raquo; est munie d&rsquo;un rabat de protection ; les trois poches arri&egrave;re vous permettront d&rsquo;emmener votre ravitaillement et une quatri&egrave;me poche zipp&eacute;e gardera vos clefs et t&eacute;l&eacute;phone en lieu s&ucirc;r. Pour votre s&eacute;curit&eacute; , deux bandes r&eacute;fl&eacute;chissantes sont appos&eacute;es sur les poches arri&egrave;re pour vous assurer une bonne visibilit&eacute;. Propos&eacute;e &eacute;galement en finition poches pixels pour une visibilit&eacute; sup&eacute;rieure.</p>', 'Veste-Thermique-Wind-Tek-Ref-1810-Z-6159a0992e7e2.png', 72, 0, 'Réf. 1810 Z'),
        (9, 'Cuissard court Lycra', '<p><strong>avec bretelles et peau TRS</strong><br />\r\nLe cuissard Classic avec l&rsquo;&eacute;lastique silicon&eacute; permettant d&rsquo;&ecirc;tre solidaire avec la jambe est conseill&eacute; pour les plus jeunes cyclistes ayant un d&eacute;ficit musculaire. Fabriqu&eacute; &agrave; partir d&#39;un tissu hautement technique de fabrication italienne, sa construction multi-panneaux offre un ajustement parfait, adapt&eacute; &agrave; votre corps. Les bretelles constitu&eacute;es de tissu a&eacute;r&eacute; ultral&eacute;ger garantissent un bon maintien au corps et cela dans toutes les positions.</p>', 'Cuissard-court-Lycra-Ref-1813-B-6159a12ce396c.png', 45, 0, 'Réf. 1813 B'),
        (10, 'Collant long super Roubaix', '<p><strong>avec bretelles et peau TRS</strong><br />\r\nLe collant en Super-Roubaix offre un maintien parfait et apporte un total confort pour vos sorties hivernales. Pr&eacute;form&eacute;, sa d&eacute;coupe est con&ccedil;ue pour r&eacute;pondre aux normes attendues par les cyclistes en termes de fonctionnalit&eacute; et de style. Il est fabriqu&eacute; &agrave; partir d&#39;un tissu hautement technique de fabrication italienne, garantissant une compression et une r&eacute;tention de forme exceptionnelles. De plus la construction multi-panneaux offre un ajustement parfait, adapt&eacute; &agrave; votre corps. Les bretelles sont aussi en Super-Roubaix pour garder la chaleur dans le dos.</p>', 'Collant-long-super-Roubaix-Ref-1816-6159a18e30905.png', 55, 0, 'Réf. 1816'),
        (11, 'Corsaire en Lycra', '<p><strong>avec bretelles et peau TRS</strong><br />\r\nLe corsaire Pr&eacute;form&eacute; Mod&egrave;le interm&eacute;diaire entre le cuissard et le collant est id&eacute;al pour les sorties de la mi-saison. Il descend sous le genou mais laisse la cheville et une partie du mollet &agrave; l&#39;air libre. Fabriqu&eacute; en Lycra 210 Gr r&eacute;f 1814. Un &eacute;lastique silicon&eacute; maintient la position du corsaire au niveau du mollet.</p>', 'Collant-long-super-Roubaix-Ref-1816-6159a1f332c02.png', 50, 0, 'Réf. 1814'),
        (12, 'Short VTT A3K', '<p><strong>(sans peau)</strong><br />\r\nCe short ultra l&eacute;ger et r&eacute;sistant en A3K est adapt&eacute; pour les sorties de VTT ou DH. Sa coupe offre un confort d&#39;utilisation tout au long de la saison et se montre particuli&egrave;rement performant pour les pratiques engag&eacute;es. 2 poches zipp&eacute;s viennent compl&egrave;ter ce mod&egrave;le totalement sublimable.</p>', 'Short-VTT-sans-peau-Ref-2110-6159a22bc6bb1.png', 40, 0, 'Réf. 2110');");
        $this->addSql("INSERT INTO `product_size` (`product_id`, `size_id`) VALUES(1, 1),(1, 3),(1, 4),(1, 5),(1, 6),(1, 7),(2, 1),(2, 2),(2, 3),(2, 4),(2, 5),(2, 6),(2, 7),(3, 1),(3, 2),(3, 3),(3, 4),(3, 5),(3, 6),(3, 7),(4, 1),(4, 2),(4, 3),(4, 4),(4, 5),(4, 6),(4, 7),(5, 1),(5, 2),(5, 3),(5, 4),(5, 5),(5, 6),(5, 7),(6, 1),(6, 2),(6, 3),(6, 4),(6, 5),(6, 6),(6, 7),(7, 1),(7, 2),(7, 3),(7, 4),(7, 5),(7, 6),(7, 7),(8, 1),(8, 2),(8, 3),(8, 4),(8, 5),(8, 6),(8, 7),(9, 1),(9, 2),(9, 3),(9, 4),(9, 5),(9, 6),(9, 7),(10, 1),(10, 2),(10, 3),(10, 4),(10, 5),(10, 6),(10, 7),(11, 1),(11, 2),(11, 3),(11, 4),(11, 5),(11, 6),(11, 7),(12, 1),(12, 2),(12, 3),(12, 4),(12, 5),(12, 6),(12, 7);");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
