# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    project_directory: '%kernel.project_dir%/'
    public_directory: '%kernel.project_dir%/public'
    uploads_directory_path: '%kernel.project_dir%/public/uploads/'
    uploads_directory: '/uploads/'
    files_directory_path: '%kernel.project_dir%/public/files/'
    products_directory: 'uploads/products'
    products_directory_path: '%kernel.project_dir%/public/%products_directory%'
    backgrounds_directory: '/images/background/'
    backgrounds_directory_path: '%kernel.project_dir%/public%backgrounds_directory%'
    data_directory_path: '%kernel.project_dir%/data/'
    tmp_directory_path: '%kernel.project_dir%/data/tmp/'
    cmd_directory_path: '%kernel.project_dir%/data/cmd/'
    documentation_directory_path: '%kernel.project_dir%/data/documentation/'
    project_directories: 
        project: '%kernel.project_dir%'
        public: 'public'
        upload: 'uploads'
        files: 'files'
        products: 'uploads/products'
        backgrounds: 'images/background'
        data: 'data'
        tmp: 'data/tmp'
        cmd: 'data/cmd'
        documentation: 'data/documentation'
    environment: '%env(APP_ENV)%'
    maintenance:
        ipAuthorized: ["127.0.0.1","88.166.188.236","86.216.124.78","81.51.249.36", "2a01:cb11:3e7:a00:44f1:6289:a76f:7283", "2a01:cb11:8a1:5000:69f7:2c40:a506:e3c4"] 

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # App\EventListeners\EntityListener:
    #     tags:
    #         - { name: doctrine.orm.entity_listener, method: content }

    App\EventListeners\MaintenanceListener:
       tags:
          - { name: kernel.event_listener, event: kernel.request }
       arguments: ['%maintenance%']

    # App\EventListeners\ExceptionListener:
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\RegistrationChangeListener:
        tags: 
            - 
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
        arguments: ['@App\Service\SeasonService']
            